name: Prod Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Access environment variables
        run: echo "The URL is ${{ secrets.URL }}"
      - name: Access secrets
        run: echo "The secret is ${{ secrets.senha }}"
